---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: infrastructure
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      memory: 32Mi
    type: Container
